version: "3"
services:
  todotests:
    build: 
      context: ./todo-app/tests
      dockerfile: Dockerfile
    depends_on:
      - "todofront"
      - "todoback"
    environment:
      - FRONT_HOST=todofront
  todofront:
    build: 
      context: ./todo-app/front-end
      dockerfile: Dockerfile
    depends_on:
      - "todoback"
    environment:
      - REACT_APP_API_HOST=todoback
    ports:
      - 3000:3000
  todoback:
    build: 
      context: ./todo-app/back-end
      dockerfile: Dockerfile
    ports:
      - 3001:3001
